### ISSUE TITLE
.col-*-offset-0 is not presented in the code

### ISSUE THREAD

**Issue by vbifonixor** [kristoferjoseph/flexboxgrid#184] opened 2016-06-21 00:53 UTC
A very useful class that helps reset the offset on a larger breakpoint, just like one in bootstrap is missing, please implement this feature as soon as you can

**Comment by denkan** [comment] 2016-07-01 11:41
+1

**Comment by kristoferjoseph** [comment] 2016-07-06 05:49
Duplicate of #175

**Closed by kristoferjoseph** 2016-07-06 05:49 UTC
